\set ON_ERROR_STOP on

-- Ejecutar como propietario de la base:
-- psql "$MIGRATION_DATABASE_URL" -v app_password="..." -f sql/provision_app_role.sql

SELECT 'CREATE ROLE sga_app NOINHERIT LOGIN NOCREATEDB NOCREATEROLE NOSUPERUSER NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sga_app')
\gexec

ALTER ROLE sga_app PASSWORD :'app_password';
GRANT CONNECT ON DATABASE sga_clean TO sga_app;
GRANT USAGE ON SCHEMA public TO sga_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sga_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sga_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sga_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO sga_app;
