"""init_sga_tables

Revision ID: 88621f65ebb0
Revises: 
Create Date: 2026-05-16 20:17:20.013332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88621f65ebb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_auditoria_accion', table_name='auditoria_operativa')
    op.drop_index('idx_auditoria_created_at', table_name='auditoria_operativa')
    op.drop_index('idx_auditoria_modulo', table_name='auditoria_operativa')
    op.drop_index('idx_auditoria_usuario_id', table_name='auditoria_operativa')
    op.drop_table('auditoria_operativa')
    op.drop_table('permisos')
    op.drop_table('roles')
    op.drop_index('idx_auditoria_archivos_empresa', table_name='auditoria_archivos')
    op.drop_index('idx_auditoria_archivos_evidencia', table_name='auditoria_archivos')
    op.drop_index('idx_auditoria_archivos_fecha', table_name='auditoria_archivos')
    op.drop_table('auditoria_archivos')
    op.alter_column('auditoria_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_eventos', 'nivel',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               comment=None,
               existing_comment='Nivel del evento: INFO, WARNING, ERROR, SECURITY.',
               existing_nullable=False)
    op.alter_column('auditoria_eventos', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Datos adicionales en JSON para auditoría técnica.',
               existing_nullable=True)
    op.drop_index('idx_auditoria_empresa_id', table_name='auditoria_eventos')
    op.drop_index('idx_auditoria_nivel', table_name='auditoria_eventos')
    op.create_index(op.f('ix_auditoria_eventos_accion'), 'auditoria_eventos', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_created_at'), 'auditoria_eventos', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_empresa_id'), 'auditoria_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_id'), 'auditoria_eventos', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_modulo'), 'auditoria_eventos', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_nivel'), 'auditoria_eventos', ['nivel'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_usuario_id'), 'auditoria_eventos', ['usuario_id'], unique=False)
    op.drop_table_comment(
        'auditoria_eventos',
        existing_comment='Bitácora central de trazabilidad del sistema SGA PRO.',
        schema=None
    )
    op.alter_column('auditoria_pro_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'modulo',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'accion',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'severidad',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_auditoria_datos_extra', table_name='auditoria_pro_eventos', postgresql_using='gin')
    op.drop_index('idx_auditoria_pro_accion', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_empresa', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_fecha', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_modulo', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_permitido', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_ruta', table_name='auditoria_pro_eventos', postgresql_using='gin')
    op.drop_index('idx_auditoria_pro_severidad', table_name='auditoria_pro_eventos')
    op.drop_index('idx_auditoria_pro_usuario', table_name='auditoria_pro_eventos')
    op.create_index(op.f('ix_auditoria_pro_eventos_accion'), 'auditoria_pro_eventos', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_creado_en'), 'auditoria_pro_eventos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_empresa_id'), 'auditoria_pro_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_modulo'), 'auditoria_pro_eventos', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_permitido'), 'auditoria_pro_eventos', ['permitido'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_request_id'), 'auditoria_pro_eventos', ['request_id'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_rol'), 'auditoria_pro_eventos', ['rol'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_severidad'), 'auditoria_pro_eventos', ['severidad'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_usuario_email'), 'auditoria_pro_eventos', ['usuario_email'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_usuario_id'), 'auditoria_pro_eventos', ['usuario_id'], unique=False)
    op.drop_column('auditoria_pro_eventos', 'metadata')
    op.alter_column('auditoria_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_auditoria_fecha', table_name='auditoria_sistema')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria_sistema')
    op.alter_column('bitacoras_dinamicas', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_bitacoras_mantenimiento_id', table_name='bitacoras_dinamicas')
    op.create_index(op.f('ix_bitacoras_dinamicas_formato_id'), 'bitacoras_dinamicas', ['formato_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_id'), 'bitacoras_dinamicas', ['id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_mantenimiento_id'), 'bitacoras_dinamicas', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_tecnico_id'), 'bitacoras_dinamicas', ['tecnico_id'], unique=False)
    op.alter_column('bitacoras_respuestas', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_bitacoras_respuestas_bitacora_id', table_name='bitacoras_respuestas')
    op.create_index(op.f('ix_bitacoras_respuestas_bitacora_id'), 'bitacoras_respuestas', ['bitacora_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_respuestas_campo_id'), 'bitacoras_respuestas', ['campo_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_respuestas_id'), 'bitacoras_respuestas', ['id'], unique=False)
    op.alter_column('categorias', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categorias', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('empresas', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('equipo_hoja_vida', 'requiere_calibracion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_operacion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_mantenimiento',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_partes',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_despiece',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_electronico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_neumatico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_mecanico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_diagnostico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_prevencion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_rehabilitacion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_analisis',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_bajo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_moderado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_alto',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_elevado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('equipo_hoja_vida_equipo_id_fkey', 'equipo_hoja_vida', type_='foreignkey')
    op.create_foreign_key(None, 'equipo_hoja_vida', 'equipos', ['equipo_id'], ['id'])
    op.drop_column('equipo_hoja_vida', 'doc_registro_sanitario')
    op.drop_column('equipo_hoja_vida', 'clasificacion_riesgo')
    op.drop_column('equipo_hoja_vida', 'clasificacion_biomedica')
    op.drop_column('equipo_hoja_vida', 'doc_factura')
    op.drop_column('equipo_hoja_vida', 'doc_permiso_comercializacion')
    op.drop_column('equipo_hoja_vida', 'doc_ingreso_almacen')
    op.drop_column('equipo_hoja_vida', 'doc_cronograma_garantia')
    op.drop_column('equipo_hoja_vida', 'doc_protocolo_mantenimiento')
    op.drop_column('equipo_hoja_vida', 'doc_registro_importacion')
    op.drop_column('equipo_hoja_vida', 'doc_guia_rapida')
    op.drop_column('equipo_hoja_vida', 'periodicidad_mantenimiento')
    op.drop_column('equipo_hoja_vida', 'periodo_calibracion')
    op.alter_column('equipos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('equipos', 'estado',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipos', 'criticidad',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('equipos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('equipos_empresa_id_fkey', 'equipos', type_='foreignkey')
    op.drop_constraint('equipos_categoria_id_fkey', 'equipos', type_='foreignkey')
    op.drop_constraint('equipos_sede_id_fkey', 'equipos', type_='foreignkey')
    op.create_foreign_key(None, 'equipos', 'sedes', ['sede_id'], ['id'])
    op.create_foreign_key(None, 'equipos', 'categorias', ['categoria_id'], ['id'])
    op.create_foreign_key(None, 'equipos', 'empresas', ['empresa_id'], ['id'])
    op.alter_column('evidencias', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evidencias', 'equipo_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_evidencias_empresa_id', table_name='evidencias')
    op.drop_index('idx_evidencias_empresa_seguridad', table_name='evidencias')
    op.drop_index('idx_evidencias_extension', table_name='evidencias')
    op.drop_index('idx_evidencias_mime_type', table_name='evidencias')
    op.drop_index('idx_evidencias_validado_seguridad', table_name='evidencias')
    op.drop_constraint('evidencias_mantenimiento_id_fkey', 'evidencias', type_='foreignkey')
    op.drop_constraint('fk_evidencias_equipo', 'evidencias', type_='foreignkey')
    op.drop_constraint('fk_evidencias_empresa_id', 'evidencias', type_='foreignkey')
    op.create_foreign_key(None, 'evidencias', 'mantenimientos', ['mantenimiento_id'], ['id'])
    op.create_foreign_key(None, 'evidencias', 'equipos', ['equipo_id'], ['id'])
    op.drop_column('evidencias', 'empresa_id')
    op.drop_column('evidencias', 'nombre_seguro')
    op.drop_column('evidencias', 'fecha_validacion_seguridad')
    op.drop_column('evidencias', 'extension')
    op.drop_column('evidencias', 'mime_type')
    op.drop_column('evidencias', 'user_agent_carga')
    op.drop_column('evidencias', 'tamano_bytes')
    op.drop_column('evidencias', 'validado_seguridad')
    op.drop_column('evidencias', 'ip_carga')
    op.alter_column('formatos_campos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('formatos_campos', 'seccion',
               existing_type=sa.VARCHAR(length=180),
               server_default=None,
               existing_nullable=False)
    op.alter_column('formatos_campos', 'tipo_campo',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_campos', 'obligatorio',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_campos', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_campos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_formatos_campos_formato_id', table_name='formatos_campos')
    op.create_index(op.f('ix_formatos_campos_formato_id'), 'formatos_campos', ['formato_id'], unique=False)
    op.create_index(op.f('ix_formatos_campos_id'), 'formatos_campos', ['id'], unique=False)
    op.alter_column('formatos_mantenimiento', 'mantenimiento_tipo',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'trabajos_realizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'datos_funcionamiento',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'repuestos_utilizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_formatos_mantenimiento_mantenimiento_id', table_name='formatos_mantenimiento')
    op.create_index(op.f('ix_formatos_mantenimiento_id'), 'formatos_mantenimiento', ['id'], unique=False)
    op.create_index(op.f('ix_formatos_mantenimiento_mantenimiento_id'), 'formatos_mantenimiento', ['mantenimiento_id'], unique=False)
    op.alter_column('hist_mantenimiento', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('hist_mantenimiento', 'mantenimiento_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('hist_mantenimiento', 'estado_anterior',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('hist_mantenimiento', 'estado_nuevo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('hist_mantenimiento', 'tecnico_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('hist_mantenimiento', 'creado_por',
               existing_type=sa.VARCHAR(length=150),
               server_default=None,
               type_=sa.String(length=120),
               existing_nullable=True)
    op.drop_index('idx_hist_mantenimiento_estado', table_name='hist_mantenimiento')
    op.drop_index('idx_hist_mantenimiento_fecha', table_name='hist_mantenimiento')
    op.drop_index('idx_hist_mantenimiento_mantenimiento', table_name='hist_mantenimiento')
    op.drop_index('idx_hist_mantenimiento_tecnico', table_name='hist_mantenimiento')
    op.create_index(op.f('ix_hist_mantenimiento_id'), 'hist_mantenimiento', ['id'], unique=False)
    op.create_index(op.f('ix_hist_mantenimiento_mantenimiento_id'), 'hist_mantenimiento', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_hist_mantenimiento_tecnico_id'), 'hist_mantenimiento', ['tecnico_id'], unique=False)
    op.alter_column('historial_mantenimiento', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('historial_mantenimiento_usuario_id_fkey', 'historial_mantenimiento', type_='foreignkey')
    op.drop_constraint('historial_mantenimiento_mantenimiento_id_fkey', 'historial_mantenimiento', type_='foreignkey')
    op.create_foreign_key(None, 'historial_mantenimiento', 'mantenimientos', ['mantenimiento_id'], ['id'])
    op.create_foreign_key(None, 'historial_mantenimiento', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('login_intentos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('login_intentos', 'exitoso',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('login_intentos', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('login_intentos', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_login_intentos_bloqueo', table_name='login_intentos')
    op.drop_index('idx_login_intentos_exitoso', table_name='login_intentos')
    op.drop_index('idx_login_intentos_fecha', table_name='login_intentos')
    op.drop_index('idx_login_intentos_ip', table_name='login_intentos')
    op.drop_index('idx_login_intentos_request', table_name='login_intentos')
    op.drop_index('idx_login_intentos_username', table_name='login_intentos')
    op.create_index(op.f('ix_login_intentos_ip_origen'), 'login_intentos', ['ip_origen'], unique=False)
    op.create_index(op.f('ix_login_intentos_username'), 'login_intentos', ['username'], unique=False)
    op.alter_column('mantenimientos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mantenimientos', 'estado',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('mantenimientos', 'latitud',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('mantenimientos', 'longitud',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_mantenimientos_empresa_id'), 'mantenimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_equipo_id'), 'mantenimientos', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_id'), 'mantenimientos', ['id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_sede_id'), 'mantenimientos', ['sede_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_tecnico_id'), 'mantenimientos', ['tecnico_id'], unique=False)
    op.create_foreign_key(None, 'mantenimientos', 'sedes', ['sede_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'mantenimientos', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.alter_column('notificaciones', 'usuario_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'empresa_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'sede_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'equipo_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'mantenimiento_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'tecnico_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'tipo',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notificaciones', 'prioridad',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notificaciones', 'leida',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_notificaciones_creado', table_name='notificaciones')
    op.drop_index('idx_notificaciones_empresa', table_name='notificaciones')
    op.drop_index('idx_notificaciones_leida', table_name='notificaciones')
    op.drop_index('idx_notificaciones_mantenimiento', table_name='notificaciones')
    op.drop_index('idx_notificaciones_prioridad', table_name='notificaciones')
    op.drop_index('idx_notificaciones_rol', table_name='notificaciones')
    op.drop_index('idx_notificaciones_tecnico', table_name='notificaciones')
    op.drop_index('idx_notificaciones_tipo', table_name='notificaciones')
    op.create_index(op.f('ix_notificaciones_empresa_id'), 'notificaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_equipo_id'), 'notificaciones', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_mantenimiento_id'), 'notificaciones', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_prioridad'), 'notificaciones', ['prioridad'], unique=False)
    op.create_index(op.f('ix_notificaciones_rol_destino'), 'notificaciones', ['rol_destino'], unique=False)
    op.create_index(op.f('ix_notificaciones_sede_id'), 'notificaciones', ['sede_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_tecnico_id'), 'notificaciones', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'usado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_password_reset_email', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_expira', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_token_hash', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_usado', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_usuario', table_name='password_reset_tokens')
    op.drop_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_constraint('fk_password_reset_usuario', 'password_reset_tokens', type_='foreignkey')
    op.alter_column('permisos_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permisos_sistema', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_permisos_modulo', table_name='permisos_sistema')
    op.drop_constraint('permisos_sistema_codigo_key', 'permisos_sistema', type_='unique')
    op.create_index(op.f('ix_permisos_sistema_codigo'), 'permisos_sistema', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_sistema_modulo'), 'permisos_sistema', ['modulo'], unique=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash SHA-256 del refresh token. Nunca guardar el token plano.',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Identificador único del refresh token para rotación y revocación.',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha en que el token fue revocado por logout o rotación.',
               existing_nullable=True)
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_revoked_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_usuario_id', table_name='refresh_tokens')
    op.drop_constraint('refresh_tokens_jti_key', 'refresh_tokens', type_='unique')
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.drop_table_comment(
        'refresh_tokens',
        existing_comment='Control de refresh tokens para sesión segura, rotación y logout real.',
        schema=None
    )
    op.alter_column('roles_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles_sistema', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_roles_codigo', table_name='roles_sistema')
    op.drop_constraint('roles_sistema_codigo_key', 'roles_sistema', type_='unique')
    op.create_index(op.f('ix_roles_sistema_codigo'), 'roles_sistema', ['codigo'], unique=True)
    op.alter_column('sedes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sedes', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('sedes_empresa_id_fkey', 'sedes', type_='foreignkey')
    op.create_foreign_key(None, 'sedes', 'empresas', ['empresa_id'], ['id'])
    op.alter_column('seguridad_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seguridad_eventos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seguridad_eventos', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_seguridad_eventos_email', table_name='seguridad_eventos')
    op.drop_index('idx_seguridad_eventos_empresa', table_name='seguridad_eventos')
    op.drop_index('idx_seguridad_eventos_evento', table_name='seguridad_eventos')
    op.drop_index('idx_seguridad_eventos_fecha', table_name='seguridad_eventos')
    op.drop_index('idx_seguridad_eventos_request', table_name='seguridad_eventos')
    op.drop_index('idx_seguridad_eventos_usuario', table_name='seguridad_eventos')
    op.alter_column('tecnicos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tecnicos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('tecnicos_usuario_id_fkey', 'tecnicos', type_='foreignkey')
    op.create_foreign_key(None, 'tecnicos', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('tipos_formatos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tipos_formatos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('tipos_formatos_codigo_key', 'tipos_formatos', type_='unique')
    op.create_index(op.f('ix_tipos_formatos_codigo'), 'tipos_formatos', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_formatos_id'), 'tipos_formatos', ['id'], unique=False)
    op.alter_column('usuarios', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('usuarios_empresa_id_fkey', 'usuarios', type_='foreignkey')
    op.drop_constraint('usuarios_rol_id_fkey', 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('usuarios', 'rol_id')
    op.alter_column('usuarios_permisos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_usuarios_permisos_usuario', table_name='usuarios_permisos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuarios_permisos_usuario', 'usuarios_permisos', ['usuario_id'], unique=False)
    op.alter_column('usuarios_permisos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('rol_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key('usuarios_rol_id_fkey', 'usuarios', 'roles_sistema', ['rol_id'], ['id'])
    op.create_foreign_key('usuarios_empresa_id_fkey', 'usuarios', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tipos_formatos_id'), table_name='tipos_formatos')
    op.drop_index(op.f('ix_tipos_formatos_codigo'), table_name='tipos_formatos')
    op.create_unique_constraint('tipos_formatos_codigo_key', 'tipos_formatos', ['codigo'])
    op.alter_column('tipos_formatos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('tipos_formatos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'tecnicos', type_='foreignkey')
    op.create_foreign_key('tecnicos_usuario_id_fkey', 'tecnicos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tecnicos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('tecnicos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('idx_seguridad_eventos_usuario', 'seguridad_eventos', ['usuario_id'], unique=False)
    op.create_index('idx_seguridad_eventos_request', 'seguridad_eventos', ['request_id'], unique=False)
    op.create_index('idx_seguridad_eventos_fecha', 'seguridad_eventos', ['creado_en'], unique=False)
    op.create_index('idx_seguridad_eventos_evento', 'seguridad_eventos', ['evento'], unique=False)
    op.create_index('idx_seguridad_eventos_empresa', 'seguridad_eventos', ['empresa_id'], unique=False)
    op.create_index('idx_seguridad_eventos_email', 'seguridad_eventos', ['usuario_email'], unique=False)
    op.alter_column('seguridad_eventos', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('seguridad_eventos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('seguridad_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'sedes', type_='foreignkey')
    op.create_foreign_key('sedes_empresa_id_fkey', 'sedes', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sedes', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('sedes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_sistema_codigo'), table_name='roles_sistema')
    op.create_unique_constraint('roles_sistema_codigo_key', 'roles_sistema', ['codigo'])
    op.create_index('ix_roles_codigo', 'roles_sistema', ['codigo'], unique=False)
    op.alter_column('roles_sistema', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('roles_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'refresh_tokens',
        'Control de refresh tokens para sesión segura, rotación y logout real.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.create_unique_constraint('refresh_tokens_jti_key', 'refresh_tokens', ['jti'])
    op.create_index('idx_refresh_tokens_usuario_id', 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_index('idx_refresh_tokens_revoked_at', 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index('idx_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=False)
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha en que el token fue revocado por logout o rotación.',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.VARCHAR(length=120),
               comment='Identificador único del refresh token para rotación y revocación.',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash SHA-256 del refresh token. Nunca guardar el token plano.',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_permisos_sistema_modulo'), table_name='permisos_sistema')
    op.drop_index(op.f('ix_permisos_sistema_codigo'), table_name='permisos_sistema')
    op.create_unique_constraint('permisos_sistema_codigo_key', 'permisos_sistema', ['codigo'])
    op.create_index('ix_permisos_modulo', 'permisos_sistema', ['modulo'], unique=False)
    op.alter_column('permisos_sistema', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('permisos_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_foreign_key('fk_password_reset_usuario', 'password_reset_tokens', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', ['token_hash'])
    op.create_index('idx_password_reset_usuario', 'password_reset_tokens', ['usuario_id'], unique=False)
    op.create_index('idx_password_reset_usado', 'password_reset_tokens', ['usado'], unique=False)
    op.create_index('idx_password_reset_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index('idx_password_reset_expira', 'password_reset_tokens', ['expira_en'], unique=False)
    op.create_index('idx_password_reset_email', 'password_reset_tokens', ['email'], unique=False)
    op.alter_column('password_reset_tokens', 'usado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tecnico_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_sede_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_rol_destino'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_prioridad'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_mantenimiento_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_equipo_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_empresa_id'), table_name='notificaciones')
    op.create_index('idx_notificaciones_tipo', 'notificaciones', ['tipo'], unique=False)
    op.create_index('idx_notificaciones_tecnico', 'notificaciones', ['tecnico_id'], unique=False)
    op.create_index('idx_notificaciones_rol', 'notificaciones', ['rol_destino'], unique=False)
    op.create_index('idx_notificaciones_prioridad', 'notificaciones', ['prioridad'], unique=False)
    op.create_index('idx_notificaciones_mantenimiento', 'notificaciones', ['mantenimiento_id'], unique=False)
    op.create_index('idx_notificaciones_leida', 'notificaciones', ['leida'], unique=False)
    op.create_index('idx_notificaciones_empresa', 'notificaciones', ['empresa_id'], unique=False)
    op.create_index('idx_notificaciones_creado', 'notificaciones', [sa.text('creado_en DESC')], unique=False)
    op.alter_column('notificaciones', 'leida',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notificaciones', 'prioridad',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'MEDIA'::character varying"),
               existing_nullable=False)
    op.alter_column('notificaciones', 'tipo',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.alter_column('notificaciones', 'tecnico_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'mantenimiento_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'equipo_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'sede_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'empresa_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notificaciones', 'usuario_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_constraint(None, 'mantenimientos', type_='foreignkey')
    op.drop_constraint(None, 'mantenimientos', type_='foreignkey')
    op.drop_index(op.f('ix_mantenimientos_tecnico_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_sede_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_equipo_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_empresa_id'), table_name='mantenimientos')
    op.alter_column('mantenimientos', 'longitud',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('mantenimientos', 'latitud',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('mantenimientos', 'estado',
               existing_type=sa.String(length=30),
               server_default=sa.text("'PROGRAMADO'::character varying"),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('mantenimientos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_login_intentos_username'), table_name='login_intentos')
    op.drop_index(op.f('ix_login_intentos_ip_origen'), table_name='login_intentos')
    op.create_index('idx_login_intentos_username', 'login_intentos', ['username'], unique=False)
    op.create_index('idx_login_intentos_request', 'login_intentos', ['request_id'], unique=False)
    op.create_index('idx_login_intentos_ip', 'login_intentos', ['ip_origen'], unique=False)
    op.create_index('idx_login_intentos_fecha', 'login_intentos', ['creado_en'], unique=False)
    op.create_index('idx_login_intentos_exitoso', 'login_intentos', ['exitoso'], unique=False)
    op.create_index('idx_login_intentos_bloqueo', 'login_intentos', ['bloqueado_hasta'], unique=False)
    op.alter_column('login_intentos', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_intentos', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('login_intentos', 'exitoso',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('login_intentos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'historial_mantenimiento', type_='foreignkey')
    op.drop_constraint(None, 'historial_mantenimiento', type_='foreignkey')
    op.create_foreign_key('historial_mantenimiento_mantenimiento_id_fkey', 'historial_mantenimiento', 'mantenimientos', ['mantenimiento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('historial_mantenimiento_usuario_id_fkey', 'historial_mantenimiento', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.alter_column('historial_mantenimiento', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_hist_mantenimiento_tecnico_id'), table_name='hist_mantenimiento')
    op.drop_index(op.f('ix_hist_mantenimiento_mantenimiento_id'), table_name='hist_mantenimiento')
    op.drop_index(op.f('ix_hist_mantenimiento_id'), table_name='hist_mantenimiento')
    op.create_index('idx_hist_mantenimiento_tecnico', 'hist_mantenimiento', ['tecnico_id'], unique=False)
    op.create_index('idx_hist_mantenimiento_mantenimiento', 'hist_mantenimiento', ['mantenimiento_id'], unique=False)
    op.create_index('idx_hist_mantenimiento_fecha', 'hist_mantenimiento', ['fecha_evento'], unique=False)
    op.create_index('idx_hist_mantenimiento_estado', 'hist_mantenimiento', ['estado_nuevo'], unique=False)
    op.alter_column('hist_mantenimiento', 'creado_por',
               existing_type=sa.String(length=120),
               server_default=sa.text("'Sistema'::character varying"),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('hist_mantenimiento', 'tecnico_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('hist_mantenimiento', 'estado_nuevo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('hist_mantenimiento', 'estado_anterior',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('hist_mantenimiento', 'mantenimiento_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('hist_mantenimiento', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_formatos_mantenimiento_mantenimiento_id'), table_name='formatos_mantenimiento')
    op.drop_index(op.f('ix_formatos_mantenimiento_id'), table_name='formatos_mantenimiento')
    op.create_index('idx_formatos_mantenimiento_mantenimiento_id', 'formatos_mantenimiento', ['mantenimiento_id'], unique=False)
    op.alter_column('formatos_mantenimiento', 'repuestos_utilizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'datos_funcionamiento',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'trabajos_realizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('formatos_mantenimiento', 'mantenimiento_tipo',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Preventivo'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_formatos_campos_id'), table_name='formatos_campos')
    op.drop_index(op.f('ix_formatos_campos_formato_id'), table_name='formatos_campos')
    op.create_index('idx_formatos_campos_formato_id', 'formatos_campos', ['formato_id'], unique=False)
    op.alter_column('formatos_campos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('formatos_campos', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('formatos_campos', 'obligatorio',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('formatos_campos', 'tipo_campo',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'checkbox'::character varying"),
               existing_nullable=True)
    op.alter_column('formatos_campos', 'seccion',
               existing_type=sa.VARCHAR(length=180),
               server_default=sa.text("'General'::character varying"),
               existing_nullable=False)
    op.alter_column('formatos_campos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.add_column('evidencias', sa.Column('ip_carga', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('validado_seguridad', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('evidencias', sa.Column('tamano_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('user_agent_carga', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('extension', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('fecha_validacion_seguridad', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('nombre_seguro', sa.VARCHAR(length=260), autoincrement=False, nullable=True))
    op.add_column('evidencias', sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.create_foreign_key('fk_evidencias_empresa_id', 'evidencias', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_evidencias_equipo', 'evidencias', 'equipos', ['equipo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('evidencias_mantenimiento_id_fkey', 'evidencias', 'mantenimientos', ['mantenimiento_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_evidencias_validado_seguridad', 'evidencias', ['validado_seguridad'], unique=False)
    op.create_index('idx_evidencias_mime_type', 'evidencias', ['mime_type'], unique=False)
    op.create_index('idx_evidencias_extension', 'evidencias', ['extension'], unique=False)
    op.create_index('idx_evidencias_empresa_seguridad', 'evidencias', ['empresa_id', 'validado_seguridad'], unique=False)
    op.create_index('idx_evidencias_empresa_id', 'evidencias', ['empresa_id'], unique=False)
    op.alter_column('evidencias', 'equipo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('evidencias', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.create_foreign_key('equipos_sede_id_fkey', 'equipos', 'sedes', ['sede_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('equipos_categoria_id_fkey', 'equipos', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('equipos_empresa_id_fkey', 'equipos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.alter_column('equipos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('equipos', 'criticidad',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'MEDIA'::character varying"),
               existing_nullable=True)
    op.alter_column('equipos', 'estado',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'OPERATIVO'::character varying"),
               existing_nullable=True)
    op.alter_column('equipos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('equipo_hoja_vida', sa.Column('periodo_calibracion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('periodicidad_mantenimiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_guia_rapida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_registro_importacion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_protocolo_mantenimiento', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_cronograma_garantia', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_ingreso_almacen', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_permiso_comercializacion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_factura', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('clasificacion_biomedica', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('clasificacion_riesgo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipo_hoja_vida', sa.Column('doc_registro_sanitario', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'equipo_hoja_vida', type_='foreignkey')
    op.create_foreign_key('equipo_hoja_vida_equipo_id_fkey', 'equipo_hoja_vida', 'equipos', ['equipo_id'], ['id'], ondelete='CASCADE')
    op.alter_column('equipo_hoja_vida', 'riesgo_elevado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_alto',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_moderado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'riesgo_bajo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_analisis',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_rehabilitacion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_prevencion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'clase_diagnostico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_mecanico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_neumatico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'plano_electronico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_despiece',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_partes',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_mantenimiento',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'manual_operacion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'requiere_calibracion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('equipo_hoja_vida', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('empresas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('empresas', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('categorias', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('categorias', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_bitacoras_respuestas_id'), table_name='bitacoras_respuestas')
    op.drop_index(op.f('ix_bitacoras_respuestas_campo_id'), table_name='bitacoras_respuestas')
    op.drop_index(op.f('ix_bitacoras_respuestas_bitacora_id'), table_name='bitacoras_respuestas')
    op.create_index('idx_bitacoras_respuestas_bitacora_id', 'bitacoras_respuestas', ['bitacora_id'], unique=False)
    op.alter_column('bitacoras_respuestas', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_bitacoras_dinamicas_tecnico_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_mantenimiento_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_formato_id'), table_name='bitacoras_dinamicas')
    op.create_index('idx_bitacoras_mantenimiento_id', 'bitacoras_dinamicas', ['mantenimiento_id'], unique=False)
    op.alter_column('bitacoras_dinamicas', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index('idx_auditoria_usuario', 'auditoria_sistema', ['usuario_id'], unique=False)
    op.create_index('idx_auditoria_fecha', 'auditoria_sistema', ['fecha'], unique=False)
    op.alter_column('auditoria_sistema', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.add_column('auditoria_pro_eventos', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_auditoria_pro_eventos_usuario_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_usuario_email'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_severidad'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_rol'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_request_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_permitido'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_modulo'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_empresa_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_creado_en'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_accion'), table_name='auditoria_pro_eventos')
    op.create_index('idx_auditoria_pro_usuario', 'auditoria_pro_eventos', ['usuario_id'], unique=False)
    op.create_index('idx_auditoria_pro_severidad', 'auditoria_pro_eventos', ['severidad'], unique=False)
    op.create_index('idx_auditoria_pro_ruta', 'auditoria_pro_eventos', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(ruta, ''::text) || ' '::text) || COALESCE(detalle, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_auditoria_pro_permitido', 'auditoria_pro_eventos', ['permitido'], unique=False)
    op.create_index('idx_auditoria_pro_modulo', 'auditoria_pro_eventos', ['modulo'], unique=False)
    op.create_index('idx_auditoria_pro_fecha', 'auditoria_pro_eventos', [sa.text('creado_en DESC')], unique=False)
    op.create_index('idx_auditoria_pro_empresa', 'auditoria_pro_eventos', ['empresa_id'], unique=False)
    op.create_index('idx_auditoria_pro_accion', 'auditoria_pro_eventos', ['accion'], unique=False)
    op.create_index('idx_auditoria_datos_extra', 'auditoria_pro_eventos', ['datos_extra'], unique=False, postgresql_using='gin')
    op.alter_column('auditoria_pro_eventos', 'severidad',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'permitido',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'accion',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'EVENTO'::character varying"),
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'modulo',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'SISTEMA'::character varying"),
               existing_nullable=False)
    op.alter_column('auditoria_pro_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'auditoria_eventos',
        'Bitácora central de trazabilidad del sistema SGA PRO.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_auditoria_eventos_usuario_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_nivel'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_modulo'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_empresa_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_created_at'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_accion'), table_name='auditoria_eventos')
    op.create_index('idx_auditoria_nivel', 'auditoria_eventos', ['nivel'], unique=False)
    op.create_index('idx_auditoria_empresa_id', 'auditoria_eventos', ['empresa_id'], unique=False)
    op.alter_column('auditoria_eventos', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos adicionales en JSON para auditoría técnica.',
               existing_nullable=True)
    op.alter_column('auditoria_eventos', 'nivel',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'INFO'::character varying"),
               comment='Nivel del evento: INFO, WARNING, ERROR, SECURITY.',
               existing_nullable=False)
    op.alter_column('auditoria_eventos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table('auditoria_archivos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuario_email', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('evidencia_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('nombre_original', sa.VARCHAR(length=260), autoincrement=False, nullable=True),
    sa.Column('nombre_seguro', sa.VARCHAR(length=260), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tamano_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('permitido', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_origen', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auditoria_archivos_pkey')
    )
    op.create_index('idx_auditoria_archivos_fecha', 'auditoria_archivos', ['creado_en'], unique=False)
    op.create_index('idx_auditoria_archivos_evidencia', 'auditoria_archivos', ['evidencia_id'], unique=False)
    op.create_index('idx_auditoria_archivos_empresa', 'auditoria_archivos', ['empresa_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('nombre', name='roles_nombre_key')
    )
    op.create_table('permisos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modulo', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permisos_pkey'),
    sa.UniqueConstraint('codigo', name='permisos_codigo_key')
    )
    op.create_table('auditoria_operativa',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuario_nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('usuario_rol', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entidad_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estado_anterior', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado_nuevo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_origen', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auditoria_operativa_pkey')
    )
    op.create_index('idx_auditoria_usuario_id', 'auditoria_operativa', ['usuario_id'], unique=False)
    op.create_index('idx_auditoria_modulo', 'auditoria_operativa', ['modulo'], unique=False)
    op.create_index('idx_auditoria_created_at', 'auditoria_operativa', ['created_at'], unique=False)
    op.create_index('idx_auditoria_accion', 'auditoria_operativa', ['accion'], unique=False)
    # ### end Alembic commands ###
