"""initial_clean_final

Revision ID: f284acc97939
Revises: 
Create Date: 2026-05-16 21:31:21.390786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f284acc97939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=180), nullable=True),
    sa.Column('usuario_rol', sa.String(length=60), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('modulo', sa.String(length=80), nullable=False),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('entidad', sa.String(length=120), nullable=True),
    sa.Column('entidad_id', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_eventos_accion'), 'auditoria_eventos', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_created_at'), 'auditoria_eventos', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_empresa_id'), 'auditoria_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_id'), 'auditoria_eventos', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_modulo'), 'auditoria_eventos', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_nivel'), 'auditoria_eventos', ['nivel'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_usuario_id'), 'auditoria_eventos', ['usuario_id'], unique=False)
    op.create_table('auditoria_pro_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('usuario_email', sa.String(length=180), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=220), nullable=True),
    sa.Column('rol', sa.String(length=60), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('recurso_tipo', sa.String(length=120), nullable=True),
    sa.Column('recurso_id', sa.String(length=120), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('ruta', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_origen', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.Column('severidad', sa.String(length=30), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('datos_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_pro_eventos_accion'), 'auditoria_pro_eventos', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_creado_en'), 'auditoria_pro_eventos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_empresa_id'), 'auditoria_pro_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_modulo'), 'auditoria_pro_eventos', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_permitido'), 'auditoria_pro_eventos', ['permitido'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_request_id'), 'auditoria_pro_eventos', ['request_id'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_rol'), 'auditoria_pro_eventos', ['rol'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_severidad'), 'auditoria_pro_eventos', ['severidad'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_usuario_email'), 'auditoria_pro_eventos', ['usuario_email'], unique=False)
    op.create_index(op.f('ix_auditoria_pro_eventos_usuario_id'), 'auditoria_pro_eventos', ['usuario_id'], unique=False)
    op.create_table('auditoria_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=150), nullable=True),
    sa.Column('usuario_rol', sa.String(length=50), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('entidad', sa.String(length=100), nullable=True),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('ip_origen', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_intentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=180), nullable=False),
    sa.Column('ip_origen', sa.String(length=80), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=180), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_intentos_ip_origen'), 'login_intentos', ['ip_origen'], unique=False)
    op.create_index(op.f('ix_login_intentos_username'), 'login_intentos', ['username'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('ip_solicitud', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('permisos_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('modulo', sa.String(length=60), nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_sistema_codigo'), 'permisos_sistema', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_sistema_modulo'), 'permisos_sistema', ['modulo'], unique=False)
    op.create_table('roles_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_sistema_codigo'), 'roles_sistema', ['codigo'], unique=True)
    op.create_table('seguridad_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('usuario_email', sa.String(length=180), nullable=True),
    sa.Column('rol', sa.String(length=60), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('evento', sa.String(length=120), nullable=False),
    sa.Column('modulo', sa.String(length=120), nullable=True),
    sa.Column('metodo', sa.String(length=12), nullable=True),
    sa.Column('ruta', sa.String(length=300), nullable=True),
    sa.Column('ip_origen', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_formatos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_formatos_codigo'), 'tipos_formatos', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_formatos_id'), 'tipos_formatos', ['id'], unique=False)
    op.create_table('formatos_campos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formato_id', sa.UUID(), nullable=False),
    sa.Column('seccion', sa.String(length=180), nullable=False),
    sa.Column('nombre_campo', sa.String(length=250), nullable=False),
    sa.Column('tipo_campo', sa.String(length=50), nullable=True),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['formato_id'], ['tipos_formatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formatos_campos_formato_id'), 'formatos_campos', ['formato_id'], unique=False)
    op.create_index(op.f('ix_formatos_campos_id'), 'formatos_campos', ['id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos_sistema.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles_sistema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('sedes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('invima', sa.String(length=100), nullable=True),
    sa.Column('codigo_id', sa.String(length=100), nullable=True),
    sa.Column('inventario', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('criticidad', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('tecnicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=150), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_permisos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos_sistema.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id')
    )
    op.create_table('equipo_hoja_vida',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('adquisicion', sa.String(length=150), nullable=True),
    sa.Column('costo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('pais_fabricacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_fabricacion', sa.Date(), nullable=True),
    sa.Column('vida_util', sa.String(length=100), nullable=True),
    sa.Column('requiere_calibracion', sa.Boolean(), nullable=True),
    sa.Column('rango_voltaje', sa.String(length=100), nullable=True),
    sa.Column('rango_presion', sa.String(length=100), nullable=True),
    sa.Column('gas_refrigerante', sa.String(length=100), nullable=True),
    sa.Column('capacidad', sa.String(length=100), nullable=True),
    sa.Column('rango_corriente', sa.String(length=100), nullable=True),
    sa.Column('rango_velocidad', sa.String(length=100), nullable=True),
    sa.Column('rango_potencia', sa.String(length=100), nullable=True),
    sa.Column('rango_temperatura', sa.String(length=100), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('rango_humedad', sa.String(length=100), nullable=True),
    sa.Column('otros', sa.Text(), nullable=True),
    sa.Column('manual_operacion', sa.Boolean(), nullable=True),
    sa.Column('manual_mantenimiento', sa.Boolean(), nullable=True),
    sa.Column('manual_partes', sa.Boolean(), nullable=True),
    sa.Column('manual_despiece', sa.Boolean(), nullable=True),
    sa.Column('plano_electronico', sa.Boolean(), nullable=True),
    sa.Column('plano_electrico', sa.Boolean(), nullable=True),
    sa.Column('plano_neumatico', sa.Boolean(), nullable=True),
    sa.Column('plano_mecanico', sa.Boolean(), nullable=True),
    sa.Column('clase_diagnostico', sa.Boolean(), nullable=True),
    sa.Column('clase_prevencion', sa.Boolean(), nullable=True),
    sa.Column('clase_rehabilitacion', sa.Boolean(), nullable=True),
    sa.Column('clase_analisis', sa.Boolean(), nullable=True),
    sa.Column('riesgo_bajo', sa.Boolean(), nullable=True),
    sa.Column('riesgo_moderado', sa.Boolean(), nullable=True),
    sa.Column('riesgo_alto', sa.Boolean(), nullable=True),
    sa.Column('riesgo_elevado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('sede_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado_inicial', sa.Text(), nullable=True),
    sa.Column('estado_inicial_equipo', sa.Text(), nullable=True),
    sa.Column('acciones_realizadas', sa.Text(), nullable=True),
    sa.Column('resultado_final', sa.Text(), nullable=True),
    sa.Column('observacion_estado', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_pausa', sa.DateTime(), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_programada', sa.DateTime(), nullable=True),
    sa.Column('latitud', sa.String(length=100), nullable=True),
    sa.Column('longitud', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_empresa_id'), 'mantenimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_equipo_id'), 'mantenimientos', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_id'), 'mantenimientos', ['id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_sede_id'), 'mantenimientos', ['sede_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_tecnico_id'), 'mantenimientos', ['tecnico_id'], unique=False)
    op.create_table('bitacoras_dinamicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('formato_id', sa.UUID(), nullable=True),
    sa.Column('estado_inicial', sa.String(length=120), nullable=True),
    sa.Column('estado_final', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('repuestos_utilizados', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['formato_id'], ['tipos_formatos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacoras_dinamicas_formato_id'), 'bitacoras_dinamicas', ['formato_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_id'), 'bitacoras_dinamicas', ['id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_mantenimiento_id'), 'bitacoras_dinamicas', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_dinamicas_tecnico_id'), 'bitacoras_dinamicas', ['tecnico_id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formatos_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('numero_ot', sa.String(length=80), nullable=True),
    sa.Column('numero_inventario', sa.String(length=120), nullable=True),
    sa.Column('ubicacion', sa.String(length=180), nullable=True),
    sa.Column('mantenimiento_tipo', sa.String(length=50), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=180), nullable=True),
    sa.Column('tecnico_auxiliar', sa.String(length=180), nullable=True),
    sa.Column('tipo_equipo', sa.String(length=80), nullable=True),
    sa.Column('trabajos_realizados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_funcionamiento', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repuestos_utilizados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_usuario', sa.Text(), nullable=True),
    sa.Column('firma_operario', sa.Text(), nullable=True),
    sa.Column('firma_coordinador', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formatos_mantenimiento_id'), 'formatos_mantenimiento', ['id'], unique=False)
    op.create_index(op.f('ix_formatos_mantenimiento_mantenimiento_id'), 'formatos_mantenimiento', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_formatos_mantenimiento_tecnico_id'), 'formatos_mantenimiento', ['tecnico_id'], unique=False)
    op.create_table('hist_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=120), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hist_mantenimiento_id'), 'hist_mantenimiento', ['id'], unique=False)
    op.create_index(op.f('ix_hist_mantenimiento_mantenimiento_id'), 'hist_mantenimiento', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_hist_mantenimiento_tecnico_id'), 'hist_mantenimiento', ['tecnico_id'], unique=False)
    op.create_table('historial_mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_destino', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('sede_id', sa.UUID(), nullable=True),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=True),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('leido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_empresa_id'), 'notificaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_equipo_id'), 'notificaciones', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_mantenimiento_id'), 'notificaciones', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_prioridad'), 'notificaciones', ['prioridad'], unique=False)
    op.create_index(op.f('ix_notificaciones_rol_destino'), 'notificaciones', ['rol_destino'], unique=False)
    op.create_index(op.f('ix_notificaciones_sede_id'), 'notificaciones', ['sede_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_tecnico_id'), 'notificaciones', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('bitacoras_respuestas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bitacora_id', sa.UUID(), nullable=False),
    sa.Column('campo_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bitacora_id'], ['bitacoras_dinamicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campo_id'], ['formatos_campos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacoras_respuestas_bitacora_id'), 'bitacoras_respuestas', ['bitacora_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_respuestas_campo_id'), 'bitacoras_respuestas', ['campo_id'], unique=False)
    op.create_index(op.f('ix_bitacoras_respuestas_id'), 'bitacoras_respuestas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitacoras_respuestas_id'), table_name='bitacoras_respuestas')
    op.drop_index(op.f('ix_bitacoras_respuestas_campo_id'), table_name='bitacoras_respuestas')
    op.drop_index(op.f('ix_bitacoras_respuestas_bitacora_id'), table_name='bitacoras_respuestas')
    op.drop_table('bitacoras_respuestas')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tecnico_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_sede_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_rol_destino'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_prioridad'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_mantenimiento_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_equipo_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_empresa_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_table('historial_mantenimiento')
    op.drop_index(op.f('ix_hist_mantenimiento_tecnico_id'), table_name='hist_mantenimiento')
    op.drop_index(op.f('ix_hist_mantenimiento_mantenimiento_id'), table_name='hist_mantenimiento')
    op.drop_index(op.f('ix_hist_mantenimiento_id'), table_name='hist_mantenimiento')
    op.drop_table('hist_mantenimiento')
    op.drop_index(op.f('ix_formatos_mantenimiento_tecnico_id'), table_name='formatos_mantenimiento')
    op.drop_index(op.f('ix_formatos_mantenimiento_mantenimiento_id'), table_name='formatos_mantenimiento')
    op.drop_index(op.f('ix_formatos_mantenimiento_id'), table_name='formatos_mantenimiento')
    op.drop_table('formatos_mantenimiento')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_bitacoras_dinamicas_tecnico_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_mantenimiento_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_id'), table_name='bitacoras_dinamicas')
    op.drop_index(op.f('ix_bitacoras_dinamicas_formato_id'), table_name='bitacoras_dinamicas')
    op.drop_table('bitacoras_dinamicas')
    op.drop_index(op.f('ix_mantenimientos_tecnico_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_sede_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_equipo_id'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_empresa_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_table('equipo_hoja_vida')
    op.drop_table('usuarios_permisos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('equipos')
    op.drop_table('usuarios')
    op.drop_table('sedes')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_formatos_campos_id'), table_name='formatos_campos')
    op.drop_index(op.f('ix_formatos_campos_formato_id'), table_name='formatos_campos')
    op.drop_table('formatos_campos')
    op.drop_index(op.f('ix_tipos_formatos_id'), table_name='tipos_formatos')
    op.drop_index(op.f('ix_tipos_formatos_codigo'), table_name='tipos_formatos')
    op.drop_table('tipos_formatos')
    op.drop_table('seguridad_eventos')
    op.drop_index(op.f('ix_roles_sistema_codigo'), table_name='roles_sistema')
    op.drop_table('roles_sistema')
    op.drop_index(op.f('ix_permisos_sistema_modulo'), table_name='permisos_sistema')
    op.drop_index(op.f('ix_permisos_sistema_codigo'), table_name='permisos_sistema')
    op.drop_table('permisos_sistema')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_login_intentos_username'), table_name='login_intentos')
    op.drop_index(op.f('ix_login_intentos_ip_origen'), table_name='login_intentos')
    op.drop_table('login_intentos')
    op.drop_table('empresas')
    op.drop_table('categorias')
    op.drop_table('auditoria_sistema')
    op.drop_index(op.f('ix_auditoria_pro_eventos_usuario_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_usuario_email'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_severidad'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_rol'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_request_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_permitido'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_modulo'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_empresa_id'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_creado_en'), table_name='auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_pro_eventos_accion'), table_name='auditoria_pro_eventos')
    op.drop_table('auditoria_pro_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_usuario_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_nivel'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_modulo'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_empresa_id'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_created_at'), table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_accion'), table_name='auditoria_eventos')
    op.drop_table('auditoria_eventos')
    # ### end Alembic commands ###
